pipeline {
  agent {
    node {
      label 'built-in'
      customWorkspace '/opt/jenkins-workspace/ratesentinel-api'
    }
  }

  environment {
    AWS_REGION = "ap-south-1"
    ACCOUNT_ID = "935967800040"
    ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/ratesentinel-api"

    CLUSTER = "ratesentinel-cluster"
    SERVICE = "ratesentinal-task-service-4fylnb6g"
    TASK_FAMILY = "ratesentinal-task"

    IMAGE_TAG = "${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            url: 'https://github.com/MayankSaxena03/ratesentinel.git'
      }
    }

    stage('Install Dependencies') {
      steps {
        sh '''
          cd apps/api
          npm ci
        '''
      }
    }

    stage('Build Application') {
      steps {
        sh '''
          cd apps/api
          npm run build
        '''
      }
    }

    stage('Build Docker Image') {
      steps {
        sh '''
          docker buildx create --use || true
          docker buildx build \
            --platform linux/amd64 \
            -f apps/api/Dockerfile \
            -t $ECR_REPO:$IMAGE_TAG \
            --load \
            .
        '''
      }
    }

    stage('Login to ECR') {
      steps {
        sh '''
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin $ECR_REPO
        '''
      }
    }

    stage('Push Image to ECR') {
      steps {
        sh '''
          docker push $ECR_REPO:$IMAGE_TAG
        '''
      }
    }

    stage('Register New Task Definition') {
      steps {
        sh '''
          aws ecs describe-task-definition \
            --task-definition $TASK_FAMILY \
            --query taskDefinition \
            > taskdef.json

          jq '
            .containerDefinitions[0].image = "'$ECR_REPO':'$IMAGE_TAG'" |
            del(
              .taskDefinitionArn,
              .revision,
              .status,
              .requiresAttributes,
              .compatibilities,
              .registeredAt,
              .registeredBy
            )
          ' taskdef.json > new-taskdef.json

          aws ecs register-task-definition \
            --cli-input-json file://new-taskdef.json
        '''
      }
    }

    stage('Deploy to ECS') {
      steps {
        sh '''
          aws ecs update-service \
            --cluster $CLUSTER \
            --service $SERVICE \
            --task-definition $TASK_FAMILY \
            --force-new-deployment
        '''
      }
    }
  }
}